spring:
  security:
    oauth2:
      client:
        registration:
          keycloak-registration:
            authorization-grant-type: client_credentials
            client-id: super-user
            client-secret: super-user-secret
        provider:
          keycloak-registration:
            issuer-uri: http://localhost:28080/realms/train-station
      resource-server:
        jwt:
          issuer-uri: http://localhost:28080/realms/train-station

logging.level:
  org:
    springframework.security: trace


