logging.level:
  org:
    springframework.security: trace

io.mwi.keycloak:
  url: http://localhost:28080
  realm: train-station
  client-id: train-tracker
  client-secret: pbNRHTGXDydeQt7aXfs8tIRfiYXSQbvf
  admin:
    id: admin-cli
    user: admin
    password: admin
  super-user:
    id: super-user
    secret: super-user-secret

