### get access token
POST http://localhost:28080/realms/train-station/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=train-tracker&password=user1&username=user1&client_secret=pbNRHTGXDydeQt7aXfs8tIRfiYXSQbvf

> {%
client.global.set("accessToken", response.body.access_token)
 %}

### PUT train location
PUT http://localhost:8080/trains/1/location
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Intercity 4",
  "destination": "Tampere",
  "speed": 65.3,
  "coordinates":  [23.774141, 61.499223]
}

### set worker location feature flag value
PUT http://localhost:8080/worker
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "numberOfItems": 4
}

###
