### create user
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "John",
  "email": "john@gmail.com",
  "password": "super-secret-123"
}

###

POST http://localhost:28080/admin/realms/master/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


###
